POST http://localhost:3002/api/notes 
content-type: application/json

{
    "userId": 1,
    "title": "quis ut nam facilis et officia qui",
    "completed": false
}

###

POST http://localhost:3002/api/notes 
